// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartConn struct {
	Connid               uint32   `protobuf:"varint,1,opt,name=connid,proto3" json:"connid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartConn) Reset()         { *m = StartConn{} }
func (m *StartConn) String() string { return proto.CompactTextString(m) }
func (*StartConn) ProtoMessage()    {}
func (*StartConn) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *StartConn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartConn.Unmarshal(m, b)
}
func (m *StartConn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartConn.Marshal(b, m, deterministic)
}
func (m *StartConn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartConn.Merge(m, src)
}
func (m *StartConn) XXX_Size() int {
	return xxx_messageInfo_StartConn.Size(m)
}
func (m *StartConn) XXX_DiscardUnknown() {
	xxx_messageInfo_StartConn.DiscardUnknown(m)
}

var xxx_messageInfo_StartConn proto.InternalMessageInfo

func (m *StartConn) GetConnid() uint32 {
	if m != nil {
		return m.Connid
	}
	return 0
}

type StopConn struct {
	Connid               uint32   `protobuf:"varint,1,opt,name=connid,proto3" json:"connid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopConn) Reset()         { *m = StopConn{} }
func (m *StopConn) String() string { return proto.CompactTextString(m) }
func (*StopConn) ProtoMessage()    {}
func (*StopConn) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *StopConn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopConn.Unmarshal(m, b)
}
func (m *StopConn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopConn.Marshal(b, m, deterministic)
}
func (m *StopConn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopConn.Merge(m, src)
}
func (m *StopConn) XXX_Size() int {
	return xxx_messageInfo_StopConn.Size(m)
}
func (m *StopConn) XXX_DiscardUnknown() {
	xxx_messageInfo_StopConn.DiscardUnknown(m)
}

var xxx_messageInfo_StopConn proto.InternalMessageInfo

func (m *StopConn) GetConnid() uint32 {
	if m != nil {
		return m.Connid
	}
	return 0
}

func init() {
	proto.RegisterType((*StartConn)(nil), "pb.StartConn")
	proto.RegisterType((*StopConn)(nil), "pb.StopConn")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe6, 0xe2, 0x0c, 0x2e, 0x49,
	0x2c, 0x2a, 0x71, 0xce, 0xcf, 0xcb, 0x13, 0x12, 0xe3, 0x62, 0x4b, 0xce, 0xcf, 0xcb, 0xcb, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d, 0x82, 0xf2, 0x94, 0x94, 0xb8, 0x38, 0x82, 0x4b, 0xf2,
	0x0b, 0xf0, 0xa9, 0x71, 0x62, 0x5d, 0xc5, 0xc4, 0x14, 0x90, 0x94, 0xc4, 0x06, 0x36, 0xda, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x38, 0xd8, 0x76, 0x56, 0x67, 0x00, 0x00, 0x00,
}
